# Generated by Django 5.1.7 on 2025-04-07 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.AlterField(
            model_name='todo',
            name='task_name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
